# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=500)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('categoria_mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mpm.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data', models.DateField(primary_key=True, serialize=False)),
                ('destaque', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DiaLiturgico',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('introducao', models.TextField()),
                ('img', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLiturgia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('posicao', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('letra', models.TextField()),
                ('cifra', models.TextField()),
                ('info', models.TextField()),
                ('link_video', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('votes', models.PositiveIntegerField(blank=True, null=True)),
                ('categorias', models.ManyToManyField(to='mpm.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('itemliturgia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mpm.ItemLiturgia')),
                ('marcacao_biblia', models.CharField(max_length=100)),
                ('texto', models.TextField()),
            ],
            bases=('mpm.itemliturgia',),
        ),
        migrations.CreateModel(
            name='SugestaoMusica',
            fields=[
                ('itemliturgia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mpm.ItemLiturgia')),
                ('avulsas', models.ManyToManyField(blank=True, related_name='avulsas', to='mpm.Musica')),
                ('categorias', models.ManyToManyField(to='mpm.Categoria')),
                ('remover', models.ManyToManyField(blank=True, related_name='remover', to='mpm.Musica')),
            ],
            bases=('mpm.itemliturgia',),
        ),
        migrations.AddField(
            model_name='itemliturgia',
            name='diaLiturgico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpm.DiaLiturgico'),
        ),
        migrations.AddField(
            model_name='data',
            name='liturgia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpm.DiaLiturgico'),
        ),
    ]
