# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
