# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('url', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('imagem', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
            ],
        ),
    ]
