# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 05:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mpm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=500)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('categoria_mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mpm.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DiaLiturgico',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('introducao', models.TextField()),
                ('img', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLiturgia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('posicao', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('letra', models.TextField()),
                ('cifra', models.TextField()),
                ('info', models.TextField()),
                ('link_video', models.URLField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('categorias', models.ManyToManyField(to='mpm.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('itemLiturgia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mpm.ItemLiturgia')),
                ('marcacao_biblia', models.CharField(max_length=100)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SugestaoMusica',
            fields=[
                ('itemLiturgia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mpm.ItemLiturgia')),
                ('avulsas', models.ManyToManyField(blank=True, related_name='avulsas', to='mpm.Musica')),
                ('categorias', models.ManyToManyField(to='mpm.Categoria')),
                ('remover', models.ManyToManyField(blank=True, related_name='remover', to='mpm.Musica')),
            ],
        ),
        migrations.AddField(
            model_name='itemliturgia',
            name='diaLiturgico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpm.DiaLiturgico'),
        ),
        migrations.AddField(
            model_name='data',
            name='liturgia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpm.DiaLiturgico'),
        ),
    ]
