# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpm', '0003_auto_20160530_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='link_lpsalmo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
