# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpm', '0004_musica_link_lpsalmo'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='tem_imagem',
            field=models.BooleanField(default=False),
        ),
    ]
