# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-01 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpm', '0005_musica_tem_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('url', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
            ],
        ),
    ]
