# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpm', '0005_musica_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musica',
            old_name='image',
            new_name='imagem',
        ),
    ]
